version: '3.8'
services:
  dbt-bigquery:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.7.4
    volumes:
      - .:/usr/app
      - ~/.dbt/:/root/.dbt/
      - ${LOCAL_BIGQUERY_KEY_FILE}:/.gcp/credentials/gcp_bigquery.json
    network_mode: host